use_frameworks!

target 'fits' do
    platform :ios, '8.0'

    pod 'Contentful'
    pod 'Mixpanel-swift'
    pod 'Firebase/Auth' 
    pod 'Firebase/Core'
    pod 'UXCam'
    pod 'Fabric'
    pod 'Digits'
    pod 'TwitterCore'
end
